### ISSUE TITLE
Can't compile programs

### ISSUE THREAD

**Issue by cristeahub** [aleksanb/hdc#28]
I get this error on multiple programs I try to compile. Is this due to macros being broken?

If I try to compile a program with macros:
![image](https://cloud.githubusercontent.com/assets/1488921/10815196/d5c6a7c2-7e2a-11e5-84b7-a021315e58c6.png)

Without macros:
![image](https://cloud.githubusercontent.com/assets/1488921/10815218/f81279a0-7e2a-11e5-80b2-1db2d6bae6df.png)

**Comment by stianjensen** [comment]
What error?

**Comment by cristeahub** [comment]
I forgot the images, I've updated the comment now.

**Comment by cristeahub** [comment]
Turns out that macros can't be compiled :joy:
